### ISSUE TITLE
Setup strategy

### ISSUE THREAD

**Issue by GromNaN** [php-fig/log-util#4]
From my understanding, this project have been created to extract [utility classes that where provided](https://github.com/php-fig/log/tree/1.1.0/Psr/Log/Test) by `psr/log ^1.1` but removed from v2 (https://github.com/php-fig/log/pull/76).

This repo should start with a **v1.0.0** that provides nothing, but require `psr/log ^1.1` which provides `TestLogger` and `LoggerInterfaceTest`.

Next, **v1.1.0** requires `psr/log ^2.0|^3.0` and `php >=8.0.0` and provides the classes that were removed from this versions. Older PHP version don't have to be supported since `psr/log >= 2.0.0` require PHP 8.0 (see [composer.json](https://github.com/php-fig/log/blob/2.0.0/composer.json#L14)).

For a project that uses the test classes, needs support for PHP 7 and allows all versions of `psr/log`, it would have the following requirements:

```
"require": {
    "psr/log": "^1.1|^2.0|3.0"
},
"require-dev": {
    "psr/log-utils": "^1.0"
}
```

Seen https://github.com/php-fig/log-util/pull/2#issuecomment-885454569, ~but they don't provide a migration path and looks outdated~ but my proposition is to not change the class names.

**Comment by Jean85** [comment]
This seems a great approach. @Seldaek do you agree?

**Comment by Seldaek** [comment]
Yup sounds good to me.

**Comment by GromNaN** [comment]
Updated the description, the version that brings the classes can be `v1.1.0`, since it will be compatible.
